# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_simplex.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

import sys
import algo_simplex
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_simplex(object):
    def setupUi(self, simplex):
        simplex.setObjectName("simplex")
        simplex.setEnabled(True)
        simplex.resize(703, 848)
        self.centralwidget = QtWidgets.QWidget(simplex)
        #self.centralwidget.setEnabled(False)
        self.centralwidget.setObjectName("centralwidget")
        self.title_lbl = QtWidgets.QLabel(self.centralwidget)
        self.title_lbl.setGeometry(QtCore.QRect(260, 10, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_lbl.setFont(font)
        self.title_lbl.setObjectName("title_lbl")
        self.fonction_gb = QtWidgets.QGroupBox(self.centralwidget)
        #self.fonction_gb.setEnabled(False)
        self.fonction_gb.setGeometry(QtCore.QRect(30, 50, 551, 141))
        self.fonction_gb.setCheckable(False)
        self.fonction_gb.setObjectName("fonction_gb")
        self.rbtn_max = QtWidgets.QRadioButton(self.fonction_gb)
        #self.rbtn_max.setEnabled(False)
        self.rbtn_max.setGeometry(QtCore.QRect(10, 30, 95, 20))
        self.rbtn_max.setObjectName("rbtn_max")
        self.rbtn_min = QtWidgets.QRadioButton(self.fonction_gb)
        #self.rbtn_min.setEnabled(False)
        self.rbtn_min.setGeometry(QtCore.QRect(120, 30, 95, 20))
        self.rbtn_min.setObjectName("rbtn_min")
        self.dsb_val1_fct = QtWidgets.QDoubleSpinBox(self.fonction_gb)
        self.dsb_val1_fct.setGeometry(QtCore.QRect(100, 70, 62, 22))
        self.dsb_val1_fct.setMaximum(100000.0)
        self.dsb_val1_fct.setMinimum(-100000.0)
        self.dsb_val1_fct.setObjectName("dsb_val1_fct")
        self.lbl_val1_fct = QtWidgets.QLabel(self.fonction_gb)
        #self.lbl_val1_fct.setEnabled(False)
        self.lbl_val1_fct.setGeometry(QtCore.QRect(20, 70, 55, 16))
        self.lbl_val1_fct.setObjectName("lbl_val1_fct")
        self.dsb_val2_fct = QtWidgets.QDoubleSpinBox(self.fonction_gb)
        #self.dsb_val2_fct.setEnabled(False)
        self.dsb_val2_fct.setGeometry(QtCore.QRect(100, 100, 62, 22))
        self.dsb_val2_fct.setMaximum(100000.0)
        self.dsb_val2_fct.setMinimum(-100000.0)
        self.dsb_val2_fct.setObjectName("dsb_val2_fct")
        self.lbl_val2_fct = QtWidgets.QLabel(self.fonction_gb)
        #self.lbl_val2_fct.setEnabled(False)
        self.lbl_val2_fct.setGeometry(QtCore.QRect(20, 100, 55, 16))
        self.lbl_val2_fct.setObjectName("lbl_val2_fct")
        self.lbl_val3_fct = QtWidgets.QLabel(self.fonction_gb)
        self.lbl_val3_fct.setEnabled(False)
        self.lbl_val3_fct.setGeometry(QtCore.QRect(400, 70, 55, 16))
        self.lbl_val3_fct.setObjectName("lbl_val3_fct")
        self.dsb_val3_fct = QtWidgets.QDoubleSpinBox(self.fonction_gb)
        self.dsb_val3_fct.setGeometry(QtCore.QRect(470, 70, 62, 22))
        self.dsb_val3_fct.setMaximum(100000.0)
        self.dsb_val3_fct.setMinimum(-100000.0)
        self.dsb_val3_fct.setEnabled(False)
        self.dsb_val3_fct.setObjectName("dsb_val3_fct")
        self.dsb_val4_fct = QtWidgets.QDoubleSpinBox(self.fonction_gb)
        self.dsb_val4_fct.setGeometry(QtCore.QRect(470, 100, 62, 22))
        self.dsb_val4_fct.setMaximum(100000.0)
        self.dsb_val4_fct.setMinimum(-100000.0)
        self.dsb_val4_fct.setObjectName("dsb_val4_fct")
        self.dsb_val4_fct.setEnabled(False)
        self.lbl_val4_fct = QtWidgets.QLabel(self.fonction_gb)
        self.lbl_val4_fct.setEnabled(False)
        self.lbl_val4_fct.setGeometry(QtCore.QRect(400, 100, 55, 16))
        self.lbl_val4_fct.setObjectName("lbl_val4_fct")
        self.ckb_val3_fct = QtWidgets.QCheckBox(self.fonction_gb)
        #self.ckb_val3_fct.setEnabled(False)
        self.ckb_val3_fct.setGeometry(QtCore.QRect(220, 70, 121, 20))
        self.ckb_val3_fct.setObjectName("ckb_val3_fct")
        self.ckb_val4_fct = QtWidgets.QCheckBox(self.fonction_gb)
        #self.ckb_val4_fct.setEnabled(False)
        self.ckb_val4_fct.setGeometry(QtCore.QRect(220, 100, 111, 20))
        self.ckb_val4_fct.setObjectName("ckb_val4_fct")
        self.contrainte1_gb = QtWidgets.QGroupBox(self.centralwidget)
        self.contrainte1_gb.setGeometry(QtCore.QRect(30, 200, 551, 141))
        self.contrainte1_gb.setObjectName("contrainte1_gb")
        self.dsb_val4_c1 = QtWidgets.QDoubleSpinBox(self.contrainte1_gb)
        self.dsb_val4_c1.setGeometry(QtCore.QRect(470, 60, 62, 22))
        self.dsb_val4_c1.setMaximum(100000.0)
        self.dsb_val4_c1.setMinimum(-100000.0)
        self.dsb_val4_c1.setObjectName("dsb_val4_c1")
        self.dsb_val4_c1.setEnabled(False)
        self.lbl_val4_c1 = QtWidgets.QLabel(self.contrainte1_gb)
        self.lbl_val4_c1.setEnabled(False)
        self.lbl_val4_c1.setGeometry(QtCore.QRect(400, 60, 55, 16))
        self.lbl_val4_c1.setObjectName("lbl_val4_c1")
        self.dsb_val3_c1 = QtWidgets.QDoubleSpinBox(self.contrainte1_gb)
        self.dsb_val3_c1.setGeometry(QtCore.QRect(470, 30, 62, 22))
        self.dsb_val3_c1.setMaximum(100000.0)
        self.dsb_val3_c1.setMinimum(-100000.0)
        self.dsb_val3_c1.setEnabled(False)
        self.dsb_val3_c1.setObjectName("dsb_val3_c1")
        self.lbl_val3_c1 = QtWidgets.QLabel(self.contrainte1_gb)
        self.lbl_val3_c1.setEnabled(False)
        self.lbl_val3_c1.setGeometry(QtCore.QRect(400, 30, 55, 16))
        self.lbl_val3_c1.setObjectName("lbl_val3_c1")
        self.lbl_val2_c1 = QtWidgets.QLabel(self.contrainte1_gb)
        #self.lbl_val2_c1.setEnabled(False)
        self.lbl_val2_c1.setGeometry(QtCore.QRect(20, 60, 55, 16))
        self.lbl_val2_c1.setObjectName("lbl_val2_c1")
        self.ckb_val4_c1 = QtWidgets.QCheckBox(self.contrainte1_gb)
        #self.ckb_val4_c1.setEnabled(False)
        self.ckb_val4_c1.setGeometry(QtCore.QRect(220, 60, 111, 20))
        self.ckb_val4_c1.setObjectName("ckb_val4_c1")
        self.lbl_val1_c1 = QtWidgets.QLabel(self.contrainte1_gb)
        #self.lbl_val1_c1.setEnabled(False)
        self.lbl_val1_c1.setGeometry(QtCore.QRect(20, 30, 55, 16))
        self.lbl_val1_c1.setObjectName("lbl_val1_c1")
        self.dsb_val1_c1 = QtWidgets.QDoubleSpinBox(self.contrainte1_gb)
        self.dsb_val1_c1.setGeometry(QtCore.QRect(100, 30, 62, 22))
        self.dsb_val1_c1.setMaximum(100000.0)
        self.dsb_val1_c1.setMinimum(-100000.0)
        self.dsb_val1_c1.setObjectName("dsb_val1_c1")
        self.dsb_val2_c1 = QtWidgets.QDoubleSpinBox(self.contrainte1_gb)
        #self.dsb_val2_c1.setEnabled(False)
        self.dsb_val2_c1.setGeometry(QtCore.QRect(100, 60, 62, 22))
        self.dsb_val2_c1.setMaximum(100000.0)
        self.dsb_val2_c1.setMinimum(-100000.0)
        self.dsb_val2_c1.setObjectName("dsb_val2_c1")
        self.ckb_val3_c1 = QtWidgets.QCheckBox(self.contrainte1_gb)
        #self.ckb_val3_c1.setEnabled(False)
        self.ckb_val3_c1.setGeometry(QtCore.QRect(220, 30, 121, 20))
        self.ckb_val3_c1.setObjectName("ckb_val3_c1")
        self.rdb_egal_c1 = QtWidgets.QRadioButton(self.contrainte1_gb)
        #self.rdb_egal_c1.setEnabled(False)
        self.rdb_egal_c1.setGeometry(QtCore.QRect(20, 100, 95, 20))
        self.rdb_egal_c1.setObjectName("rdb_egal_c1")
        self.rdb_inf_c1 = QtWidgets.QRadioButton(self.contrainte1_gb)
        self.rdb_inf_c1.setGeometry(QtCore.QRect(100, 100, 95, 20))
        self.rdb_inf_c1.setObjectName("rdb_inf_c1")
        self.rdb_sup_c1 = QtWidgets.QRadioButton(self.contrainte1_gb)
        self.rdb_sup_c1.setGeometry(QtCore.QRect(220, 100, 95, 20))
        self.rdb_sup_c1.setObjectName("rdb_sup_c1")
        self.lbl_res_c1 = QtWidgets.QLabel(self.contrainte1_gb)
        #self.lbl_res_c1.setEnabled(False)
        self.lbl_res_c1.setGeometry(QtCore.QRect(400, 100, 55, 16))
        self.lbl_res_c1.setObjectName("lbl_res_c1")
        self.dsb_res_c1 = QtWidgets.QDoubleSpinBox(self.contrainte1_gb)
        self.dsb_res_c1.setGeometry(QtCore.QRect(470, 100, 62, 22))
        self.dsb_res_c1.setMaximum(100000.0)
        self.dsb_res_c1.setMinimum(-100000.0)
        self.dsb_res_c1.setObjectName("dsb_res_c1")
        self.contrainte2_gb = QtWidgets.QGroupBox(self.centralwidget)
        self.contrainte2_gb.setGeometry(QtCore.QRect(30, 360, 551, 131))
        self.contrainte2_gb.setObjectName("contrainte2_gb")
        self.lbl_val3_c2 = QtWidgets.QLabel(self.contrainte2_gb)
        self.lbl_val3_c2.setEnabled(False)
        self.lbl_val3_c2.setGeometry(QtCore.QRect(400, 30, 55, 16))
        self.lbl_val3_c2.setObjectName("lbl_val3_c2")
        self.ckb_val4_c2 = QtWidgets.QCheckBox(self.contrainte2_gb)
        #self.ckb_val4_c2.setEnabled(False)
        self.ckb_val4_c2.setGeometry(QtCore.QRect(220, 60, 111, 20))
        self.ckb_val4_c2.setObjectName("ckb_val4_c2")
        self.ckb_val3_c2 = QtWidgets.QCheckBox(self.contrainte2_gb)
        #self.ckb_val3_c2.setEnabled(False)
        self.ckb_val3_c2.setGeometry(QtCore.QRect(220, 30, 121, 20))
        self.ckb_val3_c2.setObjectName("ckb_val3_c2")
        self.lbl_val4_c2 = QtWidgets.QLabel(self.contrainte2_gb)
        self.lbl_val4_c2.setEnabled(False)
        self.lbl_val4_c2.setGeometry(QtCore.QRect(400, 60, 55, 16))
        self.lbl_val4_c2.setObjectName("lbl_val4_c2")
        self.lbl_val2_c2 = QtWidgets.QLabel(self.contrainte2_gb)
        #self.lbl_val2_c2.setEnabled(False)
        self.lbl_val2_c2.setGeometry(QtCore.QRect(20, 60, 55, 16))
        self.lbl_val2_c2.setObjectName("lbl_val2_c2")
        self.lbl_val1_c2 = QtWidgets.QLabel(self.contrainte2_gb)
        #self.lbl_val1_c2.setEnabled(False)
        self.lbl_val1_c2.setGeometry(QtCore.QRect(20, 30, 55, 16))
        self.lbl_val1_c2.setObjectName("lbl_val1_c2")
        self.dsb_val1_c2 = QtWidgets.QDoubleSpinBox(self.contrainte2_gb)
        self.dsb_val1_c2.setGeometry(QtCore.QRect(100, 30, 62, 22))
        self.dsb_val1_c2.setMaximum(100000.0)
        self.dsb_val1_c2.setMinimum(-100000.0)
        self.dsb_val1_c2.setObjectName("dsb_val1_c2")
        self.dsb_val2_c2 = QtWidgets.QDoubleSpinBox(self.contrainte2_gb)
        #self.dsb_val2_c2.setEnabled(False)
        self.dsb_val2_c2.setGeometry(QtCore.QRect(100, 60, 62, 22))
        self.dsb_val2_c2.setMaximum(100000.0)
        self.dsb_val2_c2.setMinimum(-100000.0)
        self.dsb_val2_c2.setObjectName("dsb_val2_c2")
        self.dsb_val3_c2 = QtWidgets.QDoubleSpinBox(self.contrainte2_gb)
        self.dsb_val3_c2.setGeometry(QtCore.QRect(470, 30, 62, 22))
        self.dsb_val3_c2.setMaximum(100000.0)
        self.dsb_val3_c2.setMinimum(-100000.0)
        self.dsb_val3_c2.setEnabled(False)
        self.dsb_val3_c2.setObjectName("dsb_val3_c2")
        self.dsb_val4_c2 = QtWidgets.QDoubleSpinBox(self.contrainte2_gb)
        self.dsb_val4_c2.setGeometry(QtCore.QRect(470, 60, 62, 22))
        self.dsb_val4_c2.setMaximum(100000.0)
        self.dsb_val4_c2.setMinimum(-100000.0)
        self.dsb_val4_c2.setEnabled(False)
        self.dsb_val4_c2.setObjectName("dsb_val4_c2")
        self.dsb_res_c2 = QtWidgets.QDoubleSpinBox(self.contrainte2_gb)
        self.dsb_res_c2.setGeometry(QtCore.QRect(470, 100, 62, 22))
        self.dsb_res_c2.setMaximum(100000.0)
        self.dsb_res_c2.setMinimum(-100000.0)
        self.dsb_res_c2.setObjectName("dsb_res_c2")
        self.rdb_egal_c2 = QtWidgets.QRadioButton(self.contrainte2_gb)
        self.rdb_egal_c2.setGeometry(QtCore.QRect(20, 100, 95, 20))
        self.rdb_egal_c2.setObjectName("rdb_egal_c2")
        self.lbl_res_c2 = QtWidgets.QLabel(self.contrainte2_gb)
        #self.lbl_res_c2.setEnabled(False)
        self.lbl_res_c2.setGeometry(QtCore.QRect(400, 100, 55, 16))
        self.lbl_res_c2.setObjectName("lbl_res_c2")
        self.rdb_sup_c2 = QtWidgets.QRadioButton(self.contrainte2_gb)
        self.rdb_sup_c2.setGeometry(QtCore.QRect(220, 100, 95, 20))
        self.rdb_sup_c2.setObjectName("rdb_sup_c2")
        self.rdb_inf_c2 = QtWidgets.QRadioButton(self.contrainte2_gb)
        self.rdb_inf_c2.setGeometry(QtCore.QRect(100, 100, 95, 20))
        self.rdb_inf_c2.setObjectName("rdb_inf_c2")
        self.contrainte3_gb = QtWidgets.QGroupBox(self.centralwidget)
        self.contrainte3_gb.setGeometry(QtCore.QRect(30, 520, 551, 131))
        self.contrainte3_gb.setCheckable(True)
        self.contrainte3_gb.setChecked(False)
        self.contrainte3_gb.setObjectName("contrainte3_gb")
        self.lbl_val3_c3 = QtWidgets.QLabel(self.contrainte3_gb)
        self.lbl_val3_c3.setEnabled(False)
        self.lbl_val3_c3.setGeometry(QtCore.QRect(400, 30, 55, 16))
        self.lbl_val3_c3.setObjectName("lbl_val3_c3")
        self.ckb_val4_c3 = QtWidgets.QCheckBox(self.contrainte3_gb)
        #self.ckb_val4_c3.setEnabled(False)
        self.ckb_val4_c3.setGeometry(QtCore.QRect(220, 60, 111, 20))
        self.ckb_val4_c3.setObjectName("ckb_val4_c3")
        self.ckb_val3_c3 = QtWidgets.QCheckBox(self.contrainte3_gb)
        #self.ckb_val3_c3.setEnabled(False)
        self.ckb_val3_c3.setGeometry(QtCore.QRect(220, 30, 121, 20))
        self.ckb_val3_c3.setObjectName("ckb_val3_c3")
        self.lbl_val4_c3 = QtWidgets.QLabel(self.contrainte3_gb)
        self.lbl_val4_c3.setEnabled(False)
        self.lbl_val4_c3.setGeometry(QtCore.QRect(400, 60, 55, 16))
        self.lbl_val4_c3.setObjectName("lbl_val4_c3")
        self.lbl_val2_c3 = QtWidgets.QLabel(self.contrainte3_gb)
        #self.lbl_val2_c3.setEnabled(False)
        self.lbl_val2_c3.setGeometry(QtCore.QRect(20, 60, 55, 16))
        self.lbl_val2_c3.setObjectName("lbl_val2_c3")
        self.lbl_val1_c3 = QtWidgets.QLabel(self.contrainte3_gb)
        #self.lbl_val1_c3.setEnabled(False)
        self.lbl_val1_c3.setGeometry(QtCore.QRect(20, 30, 55, 16))
        self.lbl_val1_c3.setObjectName("lbl_val1_c3")
        self.dsb_val1_c3 = QtWidgets.QDoubleSpinBox(self.contrainte3_gb)
        self.dsb_val1_c3.setGeometry(QtCore.QRect(100, 30, 62, 22))
        self.dsb_val1_c3.setMaximum(100000.0)
        self.dsb_val1_c3.setMinimum(-100000.0)
        self.dsb_val1_c3.setObjectName("dsb_val1_c3")
        self.dsb_val2_c3 = QtWidgets.QDoubleSpinBox(self.contrainte3_gb)
        #self.dsb_val2_c3.setEnabled(False)
        self.dsb_val2_c3.setGeometry(QtCore.QRect(100, 60, 62, 22))
        self.dsb_val2_c3.setMaximum(100000.0)
        self.dsb_val2_c3.setMinimum(-100000.0)
        self.dsb_val2_c3.setObjectName("dsb_val2_c3")
        self.dsb_val3_c3 = QtWidgets.QDoubleSpinBox(self.contrainte3_gb)
        self.dsb_val3_c3.setGeometry(QtCore.QRect(470, 30, 62, 22))
        self.dsb_val3_c3.setMaximum(100000.0)
        self.dsb_val3_c3.setMinimum(-100000.0)
        self.dsb_val3_c3.setEnabled(False)
        self.dsb_val3_c3.setObjectName("dsb_val3_c3")
        self.dsb_val4_c3 = QtWidgets.QDoubleSpinBox(self.contrainte3_gb)
        self.dsb_val4_c3.setGeometry(QtCore.QRect(470, 60, 62, 22))
        self.dsb_val4_c3.setMaximum(100000.0)
        self.dsb_val4_c3.setMinimum(-100000.0)
        self.dsb_val4_c3.setEnabled(False)
        self.dsb_val4_c3.setObjectName("dsb_val4_c3")
        self.dsb_res_c3 = QtWidgets.QDoubleSpinBox(self.contrainte3_gb)
        self.dsb_res_c3.setGeometry(QtCore.QRect(470, 100, 62, 22))
        self.dsb_res_c3.setMaximum(100000.0)
        self.dsb_res_c3.setMinimum(-100000.0)
        self.dsb_res_c3.setObjectName("dsb_res_c3")
        self.rdb_inf_c3 = QtWidgets.QRadioButton(self.contrainte3_gb)
        self.rdb_inf_c3.setGeometry(QtCore.QRect(100, 100, 95, 20))
        self.rdb_inf_c3.setObjectName("rdb_inf_c3")
        self.lbl_res_c3 = QtWidgets.QLabel(self.contrainte3_gb)
        #self.lbl_res_c3.setEnabled(False)
        self.lbl_res_c3.setGeometry(QtCore.QRect(400, 100, 55, 16))
        self.lbl_res_c3.setObjectName("lbl_res_c3")
        self.rdb_sup_c3 = QtWidgets.QRadioButton(self.contrainte3_gb)
        self.rdb_sup_c3.setGeometry(QtCore.QRect(220, 100, 95, 20))
        self.rdb_sup_c3.setObjectName("rdb_sup_c3")
        self.rdb_egal_c3 = QtWidgets.QRadioButton(self.contrainte3_gb)
        self.rdb_egal_c3.setGeometry(QtCore.QRect(20, 100, 95, 20))
        self.rdb_egal_c3.setObjectName("rdb_egal_c3")
        self.contrainte4_gb = QtWidgets.QGroupBox(self.centralwidget)
        #self.contrainte4_gb.setEnabled(False)
        self.contrainte4_gb.setGeometry(QtCore.QRect(30, 680, 551, 131))
        self.contrainte4_gb.setCheckable(True)
        self.contrainte4_gb.setChecked(False)
        self.contrainte4_gb.setObjectName("contrainte4_gb")
        self.lbl_val3_c4 = QtWidgets.QLabel(self.contrainte4_gb)
        self.lbl_val3_c4.setEnabled(False)
        self.lbl_val3_c4.setGeometry(QtCore.QRect(400, 30, 55, 16))
        self.lbl_val3_c4.setObjectName("lbl_val3_c4")
        self.ckb_val4_c4 = QtWidgets.QCheckBox(self.contrainte4_gb)
        #self.ckb_val4_c4.setEnabled(False)
        self.ckb_val4_c4.setGeometry(QtCore.QRect(220, 60, 111, 20))
        self.ckb_val4_c4.setObjectName("ckb_val4_c4")
        self.ckb_val3_c4 = QtWidgets.QCheckBox(self.contrainte4_gb)
        #self.ckb_val3_c4.setEnabled(False)
        self.ckb_val3_c4.setGeometry(QtCore.QRect(220, 30, 121, 20))
        self.ckb_val3_c4.setObjectName("ckb_val3_c4")
        self.lbl_val4_c4 = QtWidgets.QLabel(self.contrainte4_gb)
        self.lbl_val4_c4.setEnabled(False)
        self.lbl_val4_c4.setGeometry(QtCore.QRect(400, 60, 55, 16))
        self.lbl_val4_c4.setObjectName("lbl_val4_c4")
        self.lbl_val2_c4 = QtWidgets.QLabel(self.contrainte4_gb)
        #self.lbl_val2_c4.setEnabled(False)
        self.lbl_val2_c4.setGeometry(QtCore.QRect(20, 60, 55, 16))
        self.lbl_val2_c4.setObjectName("lbl_val2_c4")
        self.lbl_val1_c4 = QtWidgets.QLabel(self.contrainte4_gb)
        #self.lbl_val1_c4.setEnabled(False)
        self.lbl_val1_c4.setGeometry(QtCore.QRect(20, 30, 55, 16))
        self.lbl_val1_c4.setObjectName("lbl_val1_c4")
        self.dsb_val1_c4 = QtWidgets.QDoubleSpinBox(self.contrainte4_gb)
        self.dsb_val1_c4.setGeometry(QtCore.QRect(100, 30, 62, 22))
        self.dsb_val1_c4.setMaximum(100000.0)
        self.dsb_val1_c4.setMinimum(-100000.0)
        self.dsb_val1_c4.setObjectName("dsb_val1_c4")
        self.dsb_val2_c4 = QtWidgets.QDoubleSpinBox(self.contrainte4_gb)
        #self.dsb_val2_c4.setEnabled(False)
        self.dsb_val2_c4.setGeometry(QtCore.QRect(100, 60, 62, 22))
        self.dsb_val2_c4.setMaximum(100000.0)
        self.dsb_val2_c4.setMinimum(-100000.0)
        self.dsb_val2_c4.setObjectName("dsb_val2_c4")
        self.dsb_val3_c4 = QtWidgets.QDoubleSpinBox(self.contrainte4_gb)
        self.dsb_val3_c4.setGeometry(QtCore.QRect(470, 30, 62, 22))
        self.dsb_val3_c4.setMaximum(100000.0)
        self.dsb_val3_c4.setMinimum(-100000.0)
        self.dsb_val3_c4.setEnabled(False)
        self.dsb_val3_c4.setObjectName("dsb_val3_c4")
        self.dsb_val4_c4 = QtWidgets.QDoubleSpinBox(self.contrainte4_gb)
        self.dsb_val4_c4.setGeometry(QtCore.QRect(470, 60, 62, 22))
        self.dsb_val4_c4.setMaximum(100000.0)
        self.dsb_val4_c4.setMinimum(-100000.0)
        self.dsb_val4_c4.setEnabled(False)
        self.dsb_val4_c4.setObjectName("dsb_val4_c4")
        self.dsb_res_c4 = QtWidgets.QDoubleSpinBox(self.contrainte4_gb)
        self.dsb_res_c4.setGeometry(QtCore.QRect(470, 100, 62, 22))
        self.dsb_res_c4.setMaximum(100000.0)
        self.dsb_res_c4.setMinimum(-100000.0)
        self.dsb_res_c4.setObjectName("dsb_res_c4")
        self.lbl_res_c4 = QtWidgets.QLabel(self.contrainte4_gb)
        #self.lbl_res_c4.setEnabled(False)
        self.lbl_res_c4.setGeometry(QtCore.QRect(400, 100, 55, 16))
        self.lbl_res_c4.setObjectName("lbl_res_c4")
        self.rdb_sup_c4 = QtWidgets.QRadioButton(self.contrainte4_gb)
        self.rdb_sup_c4.setGeometry(QtCore.QRect(220, 100, 95, 20))
        self.rdb_sup_c4.setObjectName("rdb_sup_c4")
        self.rdb_egal_c4 = QtWidgets.QRadioButton(self.contrainte4_gb)
        self.rdb_egal_c4.setGeometry(QtCore.QRect(20, 100, 95, 20))
        self.rdb_egal_c4.setObjectName("rdb_egal_c4")
        self.rdb_inf_c4 = QtWidgets.QRadioButton(self.contrainte4_gb)
        self.rdb_inf_c4.setGeometry(QtCore.QRect(100, 100, 95, 20))
        self.rdb_inf_c4.setObjectName("rdb_inf_c4")
        self.btn_q1 = QtWidgets.QPushButton(self.centralwidget)
        #self.btn_q1.setEnabled(False)
        self.btn_q1.setGeometry(QtCore.QRect(600, 60, 93, 28))
        self.btn_q1.setObjectName("btn_q1")
        self.btn_q2 = QtWidgets.QPushButton(self.centralwidget)
        #self.btn_q2.setEnabled(False)
        self.btn_q2.setGeometry(QtCore.QRect(600, 100, 93, 28))
        self.btn_q2.setObjectName("btn_q2")
        self.btn_q3 = QtWidgets.QPushButton(self.centralwidget)
        #self.btn_q3.setEnabled(False)
        self.btn_q3.setGeometry(QtCore.QRect(600, 140, 93, 28))
        self.btn_q3.setObjectName("btn_q3")
        self.btn_valider = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        #self.btn_valider.setEnabled(False)
        self.btn_reset.setGeometry(QtCore.QRect(600, 180, 93, 28))
        self.btn_reset.setObjectName("btn_reset")
        self.btn_valider.setGeometry(QtCore.QRect(600, 220, 93, 28))
        self.btn_valider.setObjectName("btn_valider")
        simplex.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(simplex)
        self.statusbar.setObjectName("statusbar")
        simplex.setStatusBar(self.statusbar)
        
        self.ckb_val3_c1.stateChanged.connect(self.ckb_check)
        self.ckb_val3_c2.stateChanged.connect(self.ckb_check)
        self.ckb_val3_c3.stateChanged.connect(self.ckb_check)
        self.ckb_val3_c4.stateChanged.connect(self.ckb_check)
        self.ckb_val3_fct.stateChanged.connect(self.ckb_check)
        self.ckb_val4_c1.stateChanged.connect(self.ckb_check)
        self.ckb_val4_c2.stateChanged.connect(self.ckb_check)
        self.ckb_val4_c3.stateChanged.connect(self.ckb_check)
        self.ckb_val4_c4.stateChanged.connect(self.ckb_check)
        self.ckb_val4_fct.stateChanged.connect(self.ckb_check)
        
        self.btn_q1.clicked.connect(self.set_q1)
        self.btn_q2.clicked.connect(self.set_q2)
        self.btn_q3.clicked.connect(self.set_q3)
        self.btn_reset.clicked.connect(self.reset)
        self.btn_valider.clicked.connect(self.valider)

        #app.aboutToQuit.connect(self.closeEvent)

        self.retranslateUi(simplex)
        QtCore.QMetaObject.connectSlotsByName(simplex)
        
    def retranslateUi(self, simplex):
        _translate = QtCore.QCoreApplication.translate
        simplex.setWindowTitle(_translate("simplex", "Resolution Simplex"))
        self.title_lbl.setText(_translate("simplex", "Résolution Simplex"))
        self.fonction_gb.setTitle(_translate("simplex", "Fonction objectif"))
        self.rbtn_max.setText(_translate("simplex", "Maximiser"))
        self.rbtn_min.setText(_translate("simplex", "Minimiser"))
        self.lbl_val1_fct.setText(_translate("simplex", "Valeur 1"))
        self.lbl_val2_fct.setText(_translate("simplex", "Valeur 2"))
        self.lbl_val3_fct.setText(_translate("simplex", "Valeur 3"))
        self.lbl_val4_fct.setText(_translate("simplex", "Valeur 4"))
        self.ckb_val3_fct.setText(_translate("simplex", "Activer valeur 3"))
        self.ckb_val4_fct.setText(_translate("simplex", "Activer valeur 4"))
        self.contrainte1_gb.setTitle(_translate("simplex", "Fonction contrainte 1"))
        self.lbl_val4_c1.setText(_translate("simplex", "Valeur 4"))
        self.lbl_val3_c1.setText(_translate("simplex", "Valeur 3"))
        self.lbl_val2_c1.setText(_translate("simplex", "Valeur 2"))
        self.ckb_val4_c1.setText(_translate("simplex", "Activer valeur 4"))
        self.lbl_val1_c1.setText(_translate("simplex", "Valeur 1"))
        self.ckb_val3_c1.setText(_translate("simplex", "Activer valeur 3"))
        self.rdb_egal_c1.setText(_translate("simplex", "égal"))
        self.rdb_inf_c1.setText(_translate("simplex", "inférieur"))
        self.rdb_sup_c1.setText(_translate("simplex", "supérieur"))
        self.lbl_res_c1.setText(_translate("simplex", "Résultat"))
        self.contrainte2_gb.setTitle(_translate("simplex", "Fonction contrainte 2"))
        self.lbl_val3_c2.setText(_translate("simplex", "Valeur 3"))
        self.ckb_val4_c2.setText(_translate("simplex", "Activer valeur 4"))
        self.ckb_val3_c2.setText(_translate("simplex", "Activer valeur 3"))
        self.lbl_val4_c2.setText(_translate("simplex", "Valeur 4"))
        self.lbl_val2_c2.setText(_translate("simplex", "Valeur 2"))
        self.lbl_val1_c2.setText(_translate("simplex", "Valeur 1"))
        self.rdb_egal_c2.setText(_translate("simplex", "égal"))
        self.lbl_res_c2.setText(_translate("simplex", "Résultat"))
        self.rdb_sup_c2.setText(_translate("simplex", "supérieur"))
        self.rdb_inf_c2.setText(_translate("simplex", "inférieur"))
        self.contrainte3_gb.setTitle(_translate("simplex", "Fonction contrainte 3"))
        self.lbl_val3_c3.setText(_translate("simplex", "Valeur 3"))
        self.ckb_val4_c3.setText(_translate("simplex", "Activer valeur 4"))
        self.ckb_val3_c3.setText(_translate("simplex", "Activer valeur 3"))
        self.lbl_val4_c3.setText(_translate("simplex", "Valeur 4"))
        self.lbl_val2_c3.setText(_translate("simplex", "Valeur 2"))
        self.lbl_val1_c3.setText(_translate("simplex", "Valeur 1"))
        self.rdb_inf_c3.setText(_translate("simplex", "inférieur"))
        self.lbl_res_c3.setText(_translate("simplex", "Résultat"))
        self.rdb_sup_c3.setText(_translate("simplex", "supérieur"))
        self.rdb_egal_c3.setText(_translate("simplex", "égal"))
        self.contrainte4_gb.setTitle(_translate("simplex", "Fonction contrainte 4"))
        self.lbl_val3_c4.setText(_translate("simplex", "Valeur 3"))
        self.ckb_val4_c4.setText(_translate("simplex", "Activer valeur 4"))
        self.ckb_val3_c4.setText(_translate("simplex", "Activer valeur 3"))
        self.lbl_val4_c4.setText(_translate("simplex", "Valeur 4"))
        self.lbl_val2_c4.setText(_translate("simplex", "Valeur 2"))
        self.lbl_val1_c4.setText(_translate("simplex", "Valeur 1"))
        self.lbl_res_c4.setText(_translate("simplex", "Résultat"))
        self.rdb_sup_c4.setText(_translate("simplex", "supérieur"))
        self.rdb_egal_c4.setText(_translate("simplex", "égal"))
        self.rdb_inf_c4.setText(_translate("simplex", "inférieur"))
        self.btn_q1.setText(_translate("simplex", "Question 1"))
        self.btn_q2.setText(_translate("simplex", "Question 2"))
        self.btn_q3.setText(_translate("simplex", "Question 3"))
        self.btn_reset.setText(_translate("simplex", "Reset"))
        self.btn_valider.setText(_translate("simplex", "Valider"))
        
    def ckb_check(self):
        if self.ckb_val3_fct.isChecked() :
            self.lbl_val3_fct.setEnabled(True)
            self.dsb_val3_fct.setEnabled(True)
        else:
            self.lbl_val3_fct.setEnabled(False)
            self.dsb_val3_fct.setEnabled(False)
        
        if self.ckb_val4_fct.isChecked() :
            self.lbl_val4_fct.setEnabled(True)
            self.dsb_val4_fct.setEnabled(True)
        else:
            self.lbl_val4_fct.setEnabled(False)
            self.dsb_val4_fct.setEnabled(False)
        
        if self.ckb_val3_c1.isChecked() :
            self.lbl_val3_c1.setEnabled(True)
            self.dsb_val3_c1.setEnabled(True)
        else:
            self.lbl_val3_c1.setEnabled(False)
            self.dsb_val3_c1.setEnabled(False)
        
        if self.ckb_val4_c1.isChecked() :
            self.lbl_val4_c1.setEnabled(True)
            self.dsb_val4_c1.setEnabled(True)
        else:
            self.lbl_val4_c1.setEnabled(False)
            self.dsb_val4_c1.setEnabled(False)
            
        if self.ckb_val3_c2.isChecked() :
            self.lbl_val3_c2.setEnabled(True)
            self.dsb_val3_c2.setEnabled(True)
        else:
            self.lbl_val3_c2.setEnabled(False)
            self.dsb_val3_c2.setEnabled(False)
            
        if self.ckb_val4_c2.isChecked() :
            self.lbl_val4_c2.setEnabled(True)
            self.dsb_val4_c2.setEnabled(True)
        else:
            self.lbl_val4_c2.setEnabled(False)
            self.dsb_val4_c2.setEnabled(False)
        
        if self.ckb_val3_c3.isChecked() :
            self.lbl_val3_c3.setEnabled(True)
            self.dsb_val3_c3.setEnabled(True)
        else:
            self.lbl_val3_c3.setEnabled(False)
            self.dsb_val3_c3.setEnabled(False)
            
        if self.ckb_val4_c3.isChecked() :
            self.lbl_val4_c3.setEnabled(True)
            self.dsb_val4_c3.setEnabled(True)
        else:
            self.lbl_val4_c3.setEnabled(False)
            self.dsb_val4_c3.setEnabled(False)
        
        if self.ckb_val3_c4.isChecked() :
            self.lbl_val3_c4.setEnabled(True)
            self.dsb_val3_c4.setEnabled(True)
        else:
            self.lbl_val3_c4.setEnabled(False)
            self.dsb_val3_c4.setEnabled(False)
        
        if self.ckb_val4_c4.isChecked() :
            self.lbl_val4_c4.setEnabled(True)
            self.dsb_val4_c4.setEnabled(True)
        else:
            self.lbl_val4_c4.setEnabled(False)
            self.dsb_val4_c4.setEnabled(False)
            
    
    def reset(self):
        self.contrainte3_gb.setChecked(False)
        self.contrainte4_gb.setChecked(False)
    
        self.ckb_val3_fct.setChecked(False)
        self.ckb_val3_c1.setChecked(False)
        self.ckb_val3_c2.setChecked(False)
        self.ckb_val3_c3.setChecked(False)
        self.ckb_val3_c4.setChecked(False)
        self.ckb_val4_fct.setChecked(False)
        self.ckb_val4_c1.setChecked(False)
        self.ckb_val4_c2.setChecked(False)
        self.ckb_val4_c3.setChecked(False)
        self.ckb_val4_c4.setChecked(False)
        
        self.dsb_val1_fct.setValue(0)
        self.dsb_val2_fct.setValue(0)
        self.dsb_val3_fct.setValue(0)
        self.dsb_val4_fct.setValue(0)
        
        self.dsb_val1_c1.setValue(0)
        self.dsb_val2_c1.setValue(0)
        self.dsb_val3_c1.setValue(0)
        self.dsb_val4_c1.setValue(0)
        self.dsb_res_c1.setValue(0)
        
        self.dsb_val1_c2.setValue(0)
        self.dsb_val2_c2.setValue(0)
        self.dsb_val3_c2.setValue(0)
        self.dsb_val4_c2.setValue(0)
        self.dsb_res_c2.setValue(0)
        
        self.dsb_val1_c3.setValue(0)
        self.dsb_val2_c3.setValue(0)
        self.dsb_val3_c3.setValue(0)
        self.dsb_val4_c3.setValue(0)
        self.dsb_res_c3.setValue(0)
        
        self.dsb_val1_c4.setValue(0)
        self.dsb_val2_c4.setValue(0)
        self.dsb_val3_c4.setValue(0)
        self.dsb_val4_c4.setValue(0)
        self.dsb_res_c4.setValue(0)
    
    def set_q1(self):
                
        self.rbtn_max.setChecked(True)
        self.contrainte3_gb.setChecked(True)
        self.ckb_val3_fct.setChecked(True)
        self.ckb_val3_c1.setChecked(True)
        self.ckb_val3_c2.setChecked(True)
        self.ckb_val3_c3.setChecked(True)
        
        self.dsb_val1_fct.setValue(11)
        self.dsb_val2_fct.setValue(16)
        self.dsb_val3_fct.setValue(15)
        
        self.dsb_val1_c1.setValue(1)
        self.dsb_val2_c1.setValue(2)
        self.dsb_val3_c1.setValue(1.5)
        self.dsb_res_c1.setValue(12000)
        self.rdb_inf_c1.setChecked(True)
        
        self.dsb_val1_c2.setValue(0.66)
        self.dsb_val2_c2.setValue(0.66)
        self.dsb_val3_c2.setValue(1)
        self.dsb_res_c2.setValue(4600)
        self.rdb_inf_c2.setChecked(True)
        
        self.dsb_val1_c3.setValue(0.5)
        self.dsb_val2_c3.setValue(0.33)
        self.dsb_val3_c3.setValue(0.5)
        self.dsb_res_c3.setValue(2400)
        self.rdb_inf_c3.setChecked(True)
        
    def set_q2(self):
                
        self.rbtn_min.setChecked(True)
        self.contrainte3_gb.setChecked(True)
        
        self.dsb_val1_fct.setValue(20000)
        self.dsb_val2_fct.setValue(25000)
        
        self.dsb_val1_c1.setValue(400)
        self.dsb_val2_c1.setValue(300)
        self.dsb_res_c1.setValue(25000)
        self.rdb_sup_c1.setChecked(True)
        
        self.dsb_val1_c2.setValue(300)
        self.dsb_val2_c2.setValue(400)
        self.dsb_res_c2.setValue(27000)
        self.rdb_sup_c2.setChecked(True)

        self.dsb_val1_c3.setValue(200)
        self.dsb_val2_c3.setValue(500)
        self.dsb_res_c3.setValue(30000)
        self.rdb_sup_c3.setChecked(True)


    def set_q3(self):
                
        self.rbtn_min.setChecked(True)
        
        self.contrainte3_gb.setChecked(True)
        self.contrainte4_gb.setChecked(True)
        
        self.ckb_val3_fct.setChecked(True)
        self.ckb_val3_c1.setChecked(True)
        self.ckb_val3_c2.setChecked(True)
        self.ckb_val3_c3.setChecked(True)
        self.ckb_val3_c4.setChecked(True)
        
        self.ckb_val4_fct.setChecked(True)
        self.ckb_val4_c1.setChecked(True)
        self.ckb_val4_c2.setChecked(True)
        self.ckb_val4_c3.setChecked(True)
        self.ckb_val4_c4.setChecked(True)
        
        self.dsb_val1_fct.setValue(30)
        self.dsb_val2_fct.setValue(25)
        self.dsb_val3_fct.setValue(36)
        self.dsb_val4_fct.setValue(30)
        
        self.dsb_val1_c1.setValue(1)
        self.dsb_val2_c1.setValue(1)
        self.dsb_val3_c1.setValue(0)
        self.dsb_val4_c1.setValue(0)
        self.dsb_res_c1.setValue(400)
        self.rdb_inf_c1.setChecked(True)
        
        self.dsb_val1_c2.setValue(0)
        self.dsb_val2_c2.setValue(0)
        self.dsb_val3_c2.setValue(1)
        self.dsb_val4_c2.setValue(1)
        self.dsb_res_c2.setValue(300)
        self.rdb_inf_c2.setChecked(True)
        
        self.dsb_val1_c3.setValue(1)
        self.dsb_val2_c3.setValue(0)
        self.dsb_val3_c3.setValue(1)
        self.dsb_val4_c3.setValue(0)
        self.dsb_res_c3.setValue(200)
        self.rdb_egal_c3.setChecked(True)
        
        self.dsb_val1_c4.setValue(0)
        self.dsb_val2_c4.setValue(1)
        self.dsb_val3_c4.setValue(0)
        self.dsb_val4_c4.setValue(1)
        self.dsb_res_c4.setValue(300)
        self.rdb_egal_c4.setChecked(True)
        
    def valider(self):
                
        liste_fct=[]
        liste_c1=[]
        liste_c2=[]
        liste_c3=[]
        liste_c4=[]
        type_c1=""
        type_c2=""
        type_c3=""
        type_c4=""
                
        if self.rbtn_max.isChecked() : 
            maximizer = True
        else:
            maximizer = False
            
        liste_fct.append(self.dsb_val1_fct.value()*-1)
        liste_fct.append(self.dsb_val2_fct.value()*-1)
        if self.ckb_val3_fct.isChecked():
            liste_fct.append(self.dsb_val3_fct.value()*-1)
        if self.ckb_val4_fct.isChecked():
            liste_fct.append(self.dsb_val4_fct.value()*-1)
        liste_fct.append(1)
        liste_fct.append(0)
                    
        liste_c1.append(self.dsb_val1_c1.value())
        liste_c1.append(self.dsb_val2_c1.value())
        if self.ckb_val3_c1.isChecked():
            liste_c1.append(self.dsb_val3_c1.value())
        if self.ckb_val4_c3.isChecked():
            liste_c1.append(self.dsb_val4_c1.value())
        liste_c1.append(0)
        liste_c1.append(self.dsb_res_c1.value())
                
        if self.rdb_egal_c1.isChecked():
            type_c1="egal"   
        if self.rdb_inf_c1.isChecked():
            type_c1="inf"
        if self.rdb_sup_c1.isChecked():
            type_c1="sup"
                
        liste_c2.append(self.dsb_val1_c2.value())
        liste_c2.append(self.dsb_val2_c2.value())
        if self.ckb_val3_c2.isChecked():
            liste_c2.append(self.dsb_val3_c2.value())
        if self.ckb_val4_c2.isChecked():
            liste_c2.append(self.dsb_val4_c2.value())
        liste_c2.append(0)
        liste_c2.append(self.dsb_res_c2.value())
        
        if self.rdb_egal_c2.isChecked():
            type_c2="egal"
        if self.rdb_inf_c2.isChecked():
            type_c2="inf"
        if self.rdb_sup_c2.isChecked():
            type_c2="sup"
                
        if self.contrainte3_gb.isChecked():
            liste_c3.append(self.dsb_val1_c3.value())
            liste_c3.append(self.dsb_val2_c3.value())
            if self.ckb_val3_c3.isChecked():
                liste_c3.append(self.dsb_val3_c3.value())
            if self.ckb_val4_c3.isChecked():
                liste_c3.append(self.dsb_val4_c3.value())
            liste_c3.append(0)
            liste_c3.append(self.dsb_res_c3.value())
            
            if self.rdb_egal_c3.isChecked():
                type_c3="egal"   
            if self.rdb_inf_c3.isChecked():
                type_c3="inf"
            if self.rdb_sup_c3.isChecked():
                type_c3="sup"
                
        if self.contrainte4_gb.isChecked():
            liste_c4.append(self.dsb_val1_c4.value())
            liste_c4.append(self.dsb_val2_c4.value())
            if self.ckb_val3_c4.isChecked():
                liste_c4.append(self.dsb_val3_c4.value())
            if self.ckb_val4_c4.isChecked():
                liste_c4.append(self.dsb_val4_c4.value())
            liste_c4.append(0)
            liste_c4.append(self.dsb_res_c4.value())
                
            if self.rdb_egal_c4.isChecked():
                type_c4="egal"   
            if self.rdb_inf_c4.isChecked():
                type_c4="inf"
            if self.rdb_sup_c4.isChecked():
                type_c4="sup"
                        
        print("Maximize : ")
        print(maximizer)
        print("Liste fct : ")
        print(liste_fct)
        print("Liste c1 : ")
        print(liste_c1)
        print(type_c1)
        print("Liste c2 : ")
        print(liste_c2)
        print(type_c2)
        print("Liste c3 : ")
        print(liste_c3)
        print(type_c3)
        print("Liste c4 : ")
        print(liste_c4)
        print(type_c4)
        
        algo_simplex.creation_matrice(liste_fct,liste_c1,liste_c2,liste_c3,liste_c4,type_c1,type_c2,type_c3,type_c4)
                       
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    simplex = QtWidgets.QMainWindow()
    ui = Ui_simplex()
    ui.setupUi(simplex)
    simplex.show()
    sys.exit(app.quit())

